### ISSUE TITLE
`gem bootstrap --private` for gems that are private

### ISSUE THREAD

**Issue by jbodah** [svenfuchs/gem-release#51]
I've been using bundler for bootstrapping my gems (`bundle gem my_gem`), but it hasn't been quite enough control for me. I feel like gem-release solves a lot of the issues I have with bundler in particular with give me the `gem bump` command which is awesome.

One of the things I really love about bundler is that is makes gems private by default. Most of the work I do is propietary, so I don't want to accidentally push a new gem to RubyGems. It would be great if gem-release had an option for this when bootstrapping a project.

This is how bundler solves the RubyGems push issue: https://github.com/bundler/bundler/blob/master/lib/bundler/templates/newgem/newgem.gemspec.tt#L19

**Comment by svenfuchs** [comment]
Thanks for the suggestion @jbodah! This sounds like a reasonable usecase.

`2.0.0.pre.x` gives you a lot more control over the bootstrap process. See https://github.com/svenfuchs/gem-release/pull/64

Specifically you can store custom templates in `~/.gemspec/default` (or `.gemspec/default`) or in named template groups like `~/.gemspec/private` (or `.gemspec/private`). 

E.g. in your case you could have a custom gem-release template `~/.gemspec/default/gemspec`. You could copy it from https://github.com/svenfuchs/gem-release/blob/sf-v2/lib/gem/release/templates/gemspec and customize it by adding the line from Bundler's template:

```
spec.metadata["allowed_push_host"] = "TODO: Set to 'http://mygemserver.com'"
```

Since this is your own, private file you could actually set the host there, or you could use something like `<%= ENV['MY_PRIVATE_GEM_HOST'] %>`.

Does this help?

I am going to close this here for now. Please reopen if I have misunderstood you, or if things do not work as expected.
