### ISSUE TITLE
`gem bump --help` returns the options for `gem` but the summary for `gem bump`

### ISSUE THREAD

**Issue by jbodah** [svenfuchs/gem-release#55]
```
$ gem bump --help
Usage: gem [options]

  Options:
    -v, --version VERSION            Target version: next [major|minor|patch|pre|release] or a given version number [x.x.x] (not set by default)
    -c, --[no-]commit                Perform a commit after incrementing gem version (defaults to true)
    -p, --[no-]push                  Push to the git destination (defaults to false)
    -d, --destination DESTINATION    destination git repository (defaults to origin)
    -t, --[no-]tag                   Create a git tag and push it to the git destination (defaults to false)
    -r, --[no-]release               Build gem from a gemspec and push to rubygems.org (defaults to false)
    -k, --key KEY                    When releasing: use the given API key from ~/.gem/credentials (not set by default)
        --host HOST                  When releasing: push to a gemcutter-compatible host other than rubygems.org (not set by default)


  Common Options:
    -h, --help                       Get help on this command
    -V, --[no-]verbose               Set the verbose level of output
    -q, --quiet                      Silence commands
        --config-file FILE           Use this config file instead of default
        --backtrace                  Show stack backtrace on errors
        --debug                      Turn on Ruby debugging


  Summary:
    Bump the gem version
```

**Comment by svenfuchs** [comment]
Thanks for the report, @jbodah, and sorry for not following up on this earlier.

Unfortunately Rubygems (still) makes it so that it outputs all common options for all commands, no matter if they apply to these commands at all. In this case the `--verbose`, `--config-file` and `--debug` options are not used by the command `gem bump`.

However I think you might have misread the output? Only the "Common Options" are for `gem`, while the "Options" listed are for `gem bump`

I'll see if I can somehow remove the unused options from the output.

**Comment by svenfuchs** [comment]
I've searched through this quite a bit, I cannot seem to find any reasonable hook. Rubygems is a pretty ancient codebase, to say the least, and it seems things are not as extensible as they could be.

I'm going to close this for now. 

If anyone finds a reasonable way to remove these options only if we output help for our own commands then please reopen :)
