### ISSUE TITLE
Cannot bump -v patch if current version has only 2 characters

### ISSUE THREAD

**Issue by jefvlamings** [svenfuchs/gem-release#70]
Small issue with bumping existing gems.

Steps to reproduce:
Create a gem with version number `2.0`
Bump with `gem bump -v patch`

Error message:
```
ERROR:  While executing gem ... (NoMethodError)
    undefined method `compact' for nil:NilClass
```

It took me a while to figure out where the error popped up.
The problem is that the target is not being set correctly in Gem::Release::Version::Number

**Comment by jefvlamings** [comment]
Quick fix for everyone with this issue.
First change the version number to `0.x.0` before bumping a new patch

**Comment by svenfuchs** [comment]
Thanks for the report @jefvlamings! 

I generally think version numbers that do not follow semantic versioning should be discouraged. But yes, failing with an incomprehensible error message is bad.

I've made it so that if we cannot parse the number we fail with a better message. Also, if the current version number has less than three parts (major, minor, patch) we pad them to 0.  See https://github.com/svenfuchs/gem-release/blob/master/spec/gem/release/version/number_spec.rb#L203-L285 for details.

Again, thanks a lot of the report!
